### ISSUE TITLE
separate ylim for multiple plots

### ISSUE THREAD

**Issue by jacowp357** [lvwerra/jupyterplot#2]
Is it possible to have separate y limits for multiple plots?

**Comment by lvwerra** [comment]
No, this is not supported at the moment, but I think it wouldn't require too much change in the code - I'll have a look at it over the weekend.

**Comment by lvwerra** [comment]
@jacowp357 I added the feature to use separate ylims for subplots. I bumped up the jupyterplot version on pypi. Let me know if it works as expected.
