### ISSUE TITLE
plot on output widget?

### ISSUE THREAD

**Issue by kaiaeberli** [lvwerra/jupyterplot#4]
Hi - great library! Would it be possible to plot on an ipywidget output widget?

I tried, and only the plot appears, but it won't update.

**Comment by lvwerra** [comment]
Hi, thanks! Unfortunately, I know very little about ipywidget and can not really help here. You might want to checkout out the [lrcurve](https://github.com/AndreasMadsen/python-lrcurve) library which serves as a basis for this library. Maybe Andreas Madsen can help you out. Let me know if you find a solution!

**Comment by kaiaeberli** [comment]
thanks for the response - will check there.

**Comment by lvwerra** [comment]
Thanks for the reference and good luck with your project. Closing this for now.
