### ISSUE TITLE
Dots

### ISSUE THREAD

**Issue by tomMEM** [lvwerra/jupyterplot#7]
Hello, after spending some time to get real-time display for time series in jupyter notebook I found your scripts, thank you.

It works nicely, seemingly without delay of imaging frame rates and was implemented in seconds.

Is it possible to have dots and to label y_label?
What is with "finalize" - it seems not to have any obvious effects.

Otherwise, thanks, again.
Best

T

**Comment by lvwerra** [comment]
Hi @tomMEM 

Glad you found the library useful. Dots are not available at this stage and the y_label can only be set on the right hand side (see examples in the readme) via `plot_names`.

Finalize has the effect that the resulting plot in Jupyter is persistent across sessions. So that when you start your notebook again you can see the plot from the previous session.

Hope that helps.

Cheers,
Leandro

**Comment by tomMEM** [comment]
Hello Leandro, thank you for your response and additional infos. 
I am wonder, how the jupyterplot manages to stay outside the "loop", because I cannot see a reduction in live video stream while plotting some values. Is it a traitlet based or threating? Just curious. All the best. T

**Comment by lvwerra** [comment]
Hi @tomMEM 
Not sure since jupyter-plot is a wrapper around the [python-lrcurve](https://github.com/AndreasMadsen/python-lrcurve) library. Probably best to check there :) 
Cheers, Leandro

**Comment by mustansir14** [comment]
Hello @lvwerra and @tomMEM 
I am also working on time series data and wanted to plot it real-time, but I am not sure how do I put dates in the x axis, as it strictly takes in integer or float values.
Would appreciate an answer from any one of you.

Thanks,
Mustansir

**Comment by tomMEM** [comment]
Hello @mustansir14 , indeed the x axis values have to be int or float. So you might  have to perform some transformation for the x-values. 
I am also looking for some additional settings that might allow an "oscilloscope" experience, keeping only for example a second of the time series values in the display window. 
In case you have suggestions how to do it, would be great. Best. T
